### ISSUE TITLE
Transaction report success but no Stellars received?

### ISSUE THREAD

**Issue by NVitanovic** [stellar/stellard#105]
Hi,

I've sent some Stellars to one address, and got the successful response form the server. The receiving address claims not to have received the Stellars. When I try to search on the stellar explorer for the transaction hash nothing shows up.

Here are the transaction details:
```
{
   "result" : {
      "engine_result" : "tesSUCCESS",
      "engine_result_code" : 0,
      "engine_result_message" : "The transaction was applied.",
      "status" : "success",
      "tx_blob" : "120000228000000024000001A561400000000274741168400000000000000A732004B25942CCF4AC836515C06F0D8A076EE7CDF82420D739CA435007B55BE90B2E7440A35617E3BE11AA9035033CF4CE00ED8F36B19061E03A33EE7E590D1DF1CF8F0AB12917A5F2F021CFA32324C7EB1A2849AC700893E4CB99E7BC50B63A8A01830681144B71DC2F7168BDE42274C26CA12F65BA434D64C983147A91D4AD92034D84E93057C784B7BB3D1FF8DE94",
      "tx_json" : {
         "Account" : "gf1vnXVGt346vESajCNXETV1zP2dvwSV6B",
         "Amount" : "41186321",
         "Destination" : "gUBa3u4znhmunLXfa3QsrC1kmYmmf3PQMW",
         "Fee" : "10",
         "Flags" : 2147483648,
         "Sequence" : 421,
         "SigningPubKey" : "04B25942CCF4AC836515C06F0D8A076EE7CDF82420D739CA435007B55BE90B2E",
         "TransactionType" : "Payment",
         "TxnSignature" : "A35617E3BE11AA9035033CF4CE00ED8F36B19061E03A33EE7E590D1DF1CF8F0AB12917A5F2F021CFA32324C7EB1A2849AC700893E4CB99E7BC50B63A8A018306",
         "hash" : "C705EBF03BA879373178A06E4C8C30509FA70C85D3A6455F066EA8162BC86D12"
      }
   }
}
```
Here is the exporer link:
http://stellarchain.io/view/tx/C705EBF03BA879373178A06E4C8C30509FA70C85D3A6455F066EA8162BC86D12

Can someone please explain to me where did those Stellars go, and what should I do?

Best Regards!

**Comment by thejollyrogers** [comment]
Just because the result in the HTTP response has "tesSUCCESS" does not mean that it is a successfully applied and forwarded transaction on the network. This tesSUCCESS simply means that cursory validation checks (malformed transaction, correct sequence number) were passed. Awhile later, this transaction will try to be applied, which may fail for many reasons (sending a transaction to yourself, path dry, etc). Checking the transaction hash on the network will only work if the failure was a "tec..." failure (transation engine "claimed", meaning it claimed a sequence number and a fee and is in the ledger). While the transaction will stay around awhile in the node's memory, it will eventually go away if it was not claimed, which is why you may not have seen it a little while later. Please see https://github.com/stellar/stellar-payments for an implementation that correctly handles transaction processing.
